export const USER_LOGIN_ACTION = "USER_LOGIN";
export const USER_LOGIN_FETCH_REQUESTED = "USER_LOGIN_FETCH_REQUESTED";
export const USER_LOGIN_FETCH_SUCCEEDED = "USER_LOGIN_FETCH_SUCCEEDED";
export const USER_LOGIN_FETCH_FAILED = "USER_LOGIN_FETCH_FAILED";
