export const USER_LOGIN_ACTION = "USER_LOGIN";
export const USER_LOGIN_FETCH_REQUESTED = "USER_LOGIN_FETCH_REQUESTED";
export const USER_LOGIN_FETCH_SUCCEEDED = "USER_LOGIN_FETCH_SUCCEEDED";
export const USER_LOGIN_FETCH_FAILED = "USER_LOGIN_FETCH_FAILED";
export const USER_SIGN_UP_FETCH_REQUESTED = "USER_SIGN_UP_FETCH_REQUESTED";
export const USER_SIGN_UP_FETCH_SUCCEEDED = "USER_SIGN_UP_FETCH_SUCCEEDED";
export const USER_SIGN_UP_FETCH_FAILED = "USER_SIGN_UP_FETCH_FAILED";


export const USER_INVITE_REQUESTED = "USER_INVITE_REQUESTED";
export const USER_INVITE_SUCCEEDED = "USER_INVITE_SUCCEEDED";
export const USER_INVITE_FAILED = "USER_INVITE_FAILED";


export const USER_DELETE_REQUESTED = "USER_DELETE_REQUESTED";
export const USER_DELETE_SUCCEEDED = "USER_DELETE_SUCCEEDED";
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";
